#![allow(unused)]

mod chap1_3;
mod chap4;
mod chap5;
mod chap6;
mod chap7;
mod chap8;

fn main() {
    //fn main() -> Result<(), Box<dyn std::error::Error>> {
    //chap1_3::hello_world();
    //chap1_3::variables();
    //chap1_3::changing_variables();
    //chap1_3::basic_types();
    //chap1_3::basic_type_conversion();
    //chap1_3::constants();
    //chap1_3::arrays();
    //chap1_3::functions();
    //chap1_3::multiple_return_values();
    //chap1_3::returning_nothing();
    //chap1_3::if_else();
    //chap1_3::loop_();
    //chap1_3::while_();
    //chap1_3::for_();
    //chap1_3::match_();
    //chap1_3::returning_values_from_loop();
    //chap1_3::returning_values_from_block_expressions();
    //chap1_3::calling_methods();
    //chap1_3::creating_data_in_memory();
    //chap1_3::tuple_like_structs();
    //chap1_3::enumerations();
    //chap1_3::enumerations_with_data();
    //chap4::what_are_generic_types();
    //chap4::option();
    //chap4::result();
    //chap4::gracefull_error_handling();
    //chap4::ugly_option_result_handling();
    //chap4::vectors();
    //chap5::ownership();
    //chap5::scope_based_resource_management();
    //chap5::dropping_is_hierarchical();
    //chap5::moving_ownership();
    //chap5::returning_ownership();
    //chap5::borrowing_ownership_with_references();
    //chap5::borrowing_mutable_ownership_with_references();
    //chap5::dereferencing();
    //chap5::passing_around_borrowed_data();
    //chap5::references_of_references();
    //chap5::explicit_lifetimes();
    //chap5::multiple_lifetimes();
    //chap5::static_lifetimes();
    //chap5::lifetime_in_data_types();
    //chap6::string_literals();
    //chap6::raw_string_literals();
    //chap6::string_slice();
    //chap6::chars();
    //chap6::string();
    //chap6::text_as_function_parameters();
    //chap6::building_strings();
    //chap6::formating_string();
    //chap6::converting_strings();
    //chap7::encapsulation_with_methods();
    //chap7::abstraction_with_selective_exposure();
    //chap7::polymorphism_with_traits();
    //chap7::implemented_methods_on_traits();
    //chap7::trait_inheritance();
    //chap7::dynamic_vs_static_dispatch();
    //chap7::generic_functions();
    //chap7::generic_function_shorthand();
    //chap7::box_();
    //chap8::raw_pointers();
    //chap8::the_asterisk_operator();
    //chap8::the_dot_operator();
    //chap8::smart_pointers();
    //chap8::smart_unsafe_code();
    //chap8::heep_allocated_memory();
    //chap8::failable_main_revisited() //<- No trailing semicolon
    //chap8::reference_counting();
    //chap8::sharing_access();
    //chap8::sharing_across_threads();
    chap8::combining_smart_pointers();
}
